[package]
name = "extcap"
version = "0.0.1"
authors = ["Tomas Kukosa <tkeksa@gmail.com>"]
repository = "https://github.com/tkeksa/extcap-rs"
license = "Apache-2.0 OR MIT"
description = "Crate for writing extcap Wireshark plugins."
readme = "README.md"
edition = "2018"

exclude = [
  ".github",
]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
ctrl_pipe = ["tokio/fs", "tokio-util/codec"]

[dependencies]
bytes = "0.5.3"
clap = "2.33.0"
futures = "0.3.1"
log = "0.4.8"
pcap-file = "1.1.1"
tokio = { version = "0.2.6", optional = true }
tokio-util = { version = "0.2.0", optional = true }

[dev-dependencies]
ctrlc = "3.1.3"
rand = "0.7.2"
simplelog = "0.7.4"

[dev-dependencies.tokio]
version = "0.2.6"
features = ["macros", "rt-threaded"]

[[example]]
name = "test_control_dump"
required-features = ["ctrl_pipe"]
